version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "${MYSQL_EXTERNAL_PORT}:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./db.sql:/docker-entrypoint-initdb.d/01-init.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  adminer:
    image: adminer
    container_name: adminer_container
    restart: always
    ports:
      - "${ADMINER_EXTERNAL_PORT}:8080"

  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto
    ports:
      - "${MOSQUITTO_MQTT_PORT}:1883"
      - "${MOSQUITTO_WS_PORT}:9001"
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./data:/mosquitto/data
      - ./log:/mosquitto/log
    restart: unless-stopped
  backend:
    build: ./backend
    container_name: backend_container
    restart: always
    ports:
      - "${BACKEND_EXTERNAL_PORT}:3001"
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      DB_HOST: ${DB_HOST}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_PORT: ${DB_PORT}

  frontend:
    build: ./frontend
    container_name: frontend_container
    restart: always
    ports:
      - "${FRONTEND_EXTERNAL_PORT}:80"
    depends_on:
      - backend

volumes:
  mysql_data:
